apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  database: bWxmbG93ZGI= # Base64 encoded "mlfwodb"
  username: YWRtaW4= # Base64 encoded "admin" 
  password: YWRtaW4xMjMh # Base64 encoded "admin123!"
  rootpassword: YWRtaW4xMjMh # Base64 encoded "admin123!"
---

apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
type: Opaque
data:
  user: YWRtaW4=  # Base64 encoded "admin"
  secretkey: bWxlYWRtaW4xMjMh  # Base64 encoded "mleadmin123!"

